channels:
  - conda-forge
dependencies:
  - corner=2.2.1
  - git=2.35.3
  - jax=0.4.16
  - jaxlib=0.4.14
  - matplotlib=3.5.2
  - numpy=1.22.4
  - pip=22.1.1
  - python=3.9
  - pip:
      - photerr==1.1.0
      - pzflow==3.1.1
      - showyourwork==0.4.2
